spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: yourmailid
    password: smtppassword
    emailto: emailid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true